2020-02-22 22:57:19,413 ERROR: Exception on /reset_password/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyZXNldF9wYXNzd29yZCI6MSwiZXhwIjoxNTgyNDA5MTgxLjQzNDUzNjV9._kjxSVcIw63rxQFGWtrWlwTJSweFJN5JYlyagS_rfDo [POST] [in /home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/arctickey/PycharmProjects/Blog/app/routes.py", line 165, in reset_password
    user.set_password(form.password)
AttributeError: 'User' object has no attribute 'set_passowrd'
2020-02-22 22:57:30,656 INFO: Microblog startup [in /home/arctickey/PycharmProjects/Blog/app/__init__.py:49]
2020-02-22 22:57:51,542 ERROR: Exception on /reset_password/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyZXNldF9wYXNzd29yZCI6MSwiZXhwIjoxNTgyNDA5MjYwLjQ4NjExOH0.bz4YkKnQlzeg_1hNgArnQiKlqk7hcEu0vOcCxngp9Eo [POST] [in /home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/arctickey/PycharmProjects/Blog/app/routes.py", line 165, in reset_password
    user.set_password(form.password)
  File "/home/arctickey/PycharmProjects/Blog/app/modules.py", line 36, in set_password
    self.password_hash = generate_password_hash(password)
  File "/home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/werkzeug/security.py", line 203, in generate_password_hash
    h, actual_method = _hash_internal(method, salt, password)
  File "/home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/werkzeug/security.py", line 153, in _hash_internal
    rv = pbkdf2_hex(password, salt, iterations, hashfunc=method)
  File "/home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/werkzeug/security.py", line 53, in pbkdf2_hex
    rv = pbkdf2_bin(data, salt, iterations, keylen, hashfunc)
  File "/home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/werkzeug/security.py", line 79, in pbkdf2_bin
    data = to_bytes(data)
  File "/home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/werkzeug/_compat.py", line 202, in to_bytes
    raise TypeError("Expected bytes")
TypeError: Expected bytes
2020-02-22 22:58:47,134 INFO: Microblog startup [in /home/arctickey/PycharmProjects/Blog/app/__init__.py:49]
2020-02-22 23:04:13,394 INFO: Microblog startup [in /home/arctickey/PycharmProjects/Blog/app/__init__.py:49]
2020-02-22 23:04:58,458 INFO: Microblog startup [in /home/arctickey/PycharmProjects/Blog/app/__init__.py:49]
2020-02-24 16:11:10,312 INFO: Microblog startup [in /home/arctickey/PycharmProjects/Blog/app/__init__.py:51]
2020-02-24 16:11:11,885 ERROR: Exception on /login [GET] [in /home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/arctickey/PycharmProjects/Blog/app/routes.py", line 45, in login
    return render_template('login.html', title='Sign In', form=form)
  File "/home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/jinja2/loaders.py", line 129, in load
    code = environment.compile(source, name, filename)
  File "/home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "/home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/arctickey/PycharmProjects/Blog/app/templates/login.html", line 4, in template
    {% block_app content %}
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'block_app'.
