2020-02-24 16:13:22,423 ERROR: Exception on /login [GET] [in /home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/arctickey/PycharmProjects/Blog/app/routes.py", line 45, in login
    return render_template('login.html', title='Sign In', form=form)
  File "/home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/jinja2/loaders.py", line 129, in load
    code = environment.compile(source, name, filename)
  File "/home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "/home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/arctickey/PycharmProjects/Blog/app/templates/login.html", line 8, in template
    {% wtf.quick_form(form) %}
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'wtf'. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'.
2020-02-24 16:14:58,222 INFO: Microblog startup [in /home/arctickey/PycharmProjects/Blog/app/__init__.py:51]
2020-02-24 16:16:43,716 INFO: Microblog startup [in /home/arctickey/PycharmProjects/Blog/app/__init__.py:51]
2020-02-24 16:20:40,618 INFO: Microblog startup [in /home/arctickey/PycharmProjects/Blog/app/__init__.py:51]
2020-02-24 16:21:32,680 INFO: Microblog startup [in /home/arctickey/PycharmProjects/Blog/app/__init__.py:51]
2020-02-24 16:30:12,485 INFO: Microblog startup [in /home/arctickey/PycharmProjects/Blog/app/__init__.py:53]
2020-02-24 16:33:11,567 INFO: Microblog startup [in /home/arctickey/PycharmProjects/Blog/app/__init__.py:53]
2020-02-24 16:33:29,633 INFO: Microblog startup [in /home/arctickey/PycharmProjects/Blog/app/__init__.py:53]
2020-02-24 16:35:47,620 INFO: Microblog startup [in /home/arctickey/PycharmProjects/Blog/app/__init__.py:53]
2020-02-24 16:36:59,480 INFO: Microblog startup [in /home/arctickey/PycharmProjects/Blog/app/__init__.py:53]
2020-02-24 17:37:07,365 INFO: Microblog startup [in /home/arctickey/PycharmProjects/Blog/app/__init__.py:56]
2020-02-24 22:39:15,098 INFO: Microblog startup [in /home/arctickey/PycharmProjects/Blog/app/__init__.py:56]
2020-02-24 22:39:39,473 INFO: Microblog startup [in /home/arctickey/PycharmProjects/Blog/app/__init__.py:56]
2020-02-24 22:39:59,401 INFO: Microblog startup [in /home/arctickey/PycharmProjects/Blog/app/__init__.py:56]
2020-02-24 22:40:03,307 INFO: Microblog startup [in /home/arctickey/PycharmProjects/Blog/app/__init__.py:56]
2020-02-24 22:40:29,275 INFO: Microblog startup [in /home/arctickey/PycharmProjects/Blog/app/__init__.py:56]
2020-02-24 22:40:53,054 INFO: Microblog startup [in /home/arctickey/PycharmProjects/Blog/app/__init__.py:56]
2020-02-24 22:41:29,891 INFO: Microblog startup [in /home/arctickey/PycharmProjects/Blog/app/__init__.py:56]
2020-02-24 22:57:44,192 ERROR: Exception on /login [POST] [in /home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/flask/app.py", line 1969, in finalize_request
    response = self.process_response(response)
  File "/home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/flask/app.py", line 2266, in process_response
    response = handler(response)
  File "/home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/flask_login/login_manager.py", line 407, in _update_remember_cookie
    self._set_cookie(response)
  File "/home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/flask_login/login_manager.py", line 429, in _set_cookie
    data = encode_cookie(text_type(session['_user_id']))
  File "/home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/flask_login/utils.py", line 41, in encode_cookie
    return u'{0}|{1}'.format(payload, _cookie_digest(payload, key=key))
  File "/home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/flask_login/utils.py", line 352, in _cookie_digest
    key = _secret_key(key)
  File "/home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/flask_login/utils.py", line 387, in _secret_key
    key = key.encode('latin1')  # ensure bytes
UnicodeEncodeError: 'latin-1' codec can't encode character '\u0142' in position 4: ordinal not in range(256)
2020-02-24 22:59:58,450 INFO: Microblog startup [in /home/arctickey/PycharmProjects/Blog/app/__init__.py:56]
2020-02-24 23:00:24,393 ERROR: Exception on /login [POST] [in /home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/flask/app.py", line 1969, in finalize_request
    response = self.process_response(response)
  File "/home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/flask/app.py", line 2266, in process_response
    response = handler(response)
  File "/home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/flask_login/login_manager.py", line 407, in _update_remember_cookie
    self._set_cookie(response)
  File "/home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/flask_login/login_manager.py", line 429, in _set_cookie
    data = encode_cookie(text_type(session['_user_id']))
  File "/home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/flask_login/utils.py", line 41, in encode_cookie
    return u'{0}|{1}'.format(payload, _cookie_digest(payload, key=key))
  File "/home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/flask_login/utils.py", line 352, in _cookie_digest
    key = _secret_key(key)
  File "/home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/flask_login/utils.py", line 387, in _secret_key
    key = key.encode('latin1')  # ensure bytes
UnicodeEncodeError: 'latin-1' codec can't encode character '\u0142' in position 4: ordinal not in range(256)
2020-02-24 23:02:39,274 INFO: Microblog startup [in /home/arctickey/PycharmProjects/Blog/app/__init__.py:56]
