2020-02-22 15:52:39,886 ERROR: Exception on /reset_password_request [GET] [in /home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/arctickey/PycharmProjects/Blog/app/routes.py", line 154, in reset_password_request
    return render_template('reset_password_request.html',form=form,title='Password reset')
  File "/home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/arctickey/PycharmProjects/Blog/app/templates/reset_password_request.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/arctickey/PycharmProjects/Blog/app/templates/base.html", line 31, in top-level template code
    {% block content %}{% endblock %}
  File "/home/arctickey/PycharmProjects/Blog/app/templates/reset_password_request.html", line 10, in block "content"
    {% for error in form.email.errors %}
  File "/home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 471, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'app.forms.ResetPasswordRequestForm object' has no attribute 'email'
2020-02-22 15:52:49,408 INFO: Microblog startup [in /home/arctickey/PycharmProjects/Blog/app/__init__.py:49]
2020-02-22 15:53:07,029 ERROR: Exception on /reset_password_request [POST] [in /home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/arctickey/PycharmProjects/Blog/app/routes.py", line 149, in reset_password_request
    user = User.query.filter_by(email = form.email.data).first()
AttributeError: 'ResetPasswordRequestForm' object has no attribute 'email'
2020-02-22 15:53:30,455 INFO: Microblog startup [in /home/arctickey/PycharmProjects/Blog/app/__init__.py:49]
2020-02-22 15:53:39,846 ERROR: Exception on /reset_password_request [POST] [in /home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/arctickey/PycharmProjects/Blog/app/routes.py", line 151, in reset_password_request
    send_password_request_email(user)
  File "/home/arctickey/PycharmProjects/Blog/app/email.py", line 12, in send_password_request_email
    token = user.get_reset_password_token(user)
  File "/home/arctickey/PycharmProjects/Blog/app/modules.py", line 64, in get_reset_password_token
    return jwt.encode({'reset_password':self.id,'time':time() + expires_in,},
TypeError: unsupported operand type(s) for +: 'float' and 'User'
2020-02-22 15:55:14,731 INFO: Microblog startup [in /home/arctickey/PycharmProjects/Blog/app/__init__.py:49]
2020-02-22 15:55:25,121 ERROR: Exception on /reset_password_request [POST] [in /home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/arctickey/PycharmProjects/Blog/app/routes.py", line 151, in reset_password_request
    send_password_request_email(user)
  File "/home/arctickey/PycharmProjects/Blog/app/email.py", line 12, in send_password_request_email
    token = user.get_reset_password_token(user)
  File "/home/arctickey/PycharmProjects/Blog/app/modules.py", line 64, in get_reset_password_token
    return jwt.encode({'reset_password': self.id, 'time': time() + expires_in},
TypeError: unsupported operand type(s) for +: 'float' and 'User'
2020-02-22 15:56:40,514 INFO: Microblog startup [in /home/arctickey/PycharmProjects/Blog/app/__init__.py:49]
2020-02-22 15:56:49,049 ERROR: Exception on /reset_password_request [POST] [in /home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/arctickey/PycharmProjects/Blog/venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/arctickey/PycharmProjects/Blog/app/routes.py", line 151, in reset_password_request
    send_password_request_email(user)
  File "/home/arctickey/PycharmProjects/Blog/app/email.py", line 12, in send_password_request_email
    token = user.get_reset_password_token(user)
  File "/home/arctickey/PycharmProjects/Blog/app/modules.py", line 65, in get_reset_password_token
    {'reset_password': self.id, 'exp': time() + expires_in},
TypeError: unsupported operand type(s) for +: 'float' and 'User'
2020-02-22 15:58:00,550 INFO: Microblog startup [in /home/arctickey/PycharmProjects/Blog/app/__init__.py:49]
